# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

name: "Academo.org - Free, interactive, education."
description: "Education through demonstration"

url: "https://academo.org"

jquery_path: "https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"

assets_server: "https://s3-us-west-2.amazonaws.com/academo-assets"
dev_mode: false


defaults:
  -
    scope:
      path: "demos"
    values:
      layout: "demo"

markdown: rdiscount
permalink: pretty

exclude: ['README.md', 'rakefile', 'RakeHelpers.rb']

sass:
  sass_dir: scss
  style: :compressed
